### ISSUE TITLE
Serenity/JS 3.0 - New website - Replace ESDoc with Docusaurus

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1197]
We've reached the limits of what [ESDoc](https://esdoc.org/) is able to offer, and since the project is no longer maintained, we should switch to a more modern documentation generator.

I've experimented with [Docusaurus v2](https://docusaurus.io/) and it seems like the best candidate for what we're after, so:
- static generator for the Serenity/JS Handbook
- support for blog / announcements
- support for API docs generation (via TypeDoc and the [TypeDoc API plugin](https://www.npmjs.com/package/docusaurus-plugin-typedoc-api))

It would be great to include website replacement in 3.0 (or shortly after that) since we had to review all the articles anyway #1157

Results of my quick PoC:
<img width="1818" alt="Screenshot 2022-04-19 at 13 52 01" src="https://user-images.githubusercontent.com/1089173/164008353-971e29a5-c7d6-404f-80ee-bc025bb32ec8.png">
<img width="1818" alt="Screenshot 2022-04-19 at 13 52 13" src="https://user-images.githubusercontent.com/1089173/164008362-054ac902-c8b5-4418-9eb8-9558a893f3e1.png">

New website has dependencies on:
- https://github.com/milesj/docusaurus-plugin-typedoc-api/pull/35 
- https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/36

cc: @viper3400 

## Scope

- [x] New homepage
- [ ] Migrate Serenity/JS Handbook from the old website
- [ ] Update Readme files
  - [ ] assertions 
  - [ ] console-reporter
  - [ ] core  
  - [ ] cucumber
  - [ ] jasmine
  - [ ] local-server
  - [ ] mocha
  - [ ] playwright 
  - [ ] protractor
  - [ ] rest
  - [ ] serenity-bdd
  - [ ] web
  - [ ] webdriverio
- [x] Aggregate changelogs and migration guides in one place 
- [ ] Prepare a contributors' guide
- [ ] New GitHub Sponsors page
- [x] Refactor Serenity/JS modules so that the directory structure matches the documentation structure (#1258)
- [x] Document public APIs (#1258)
- [ ] Update API docs
  - [ ] Review all methods that declare `@throws` to benefit from https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/61
  - [ ] Review all methods that declare a "tip" to benefit from https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/62

**Comment by viper3400** [comment]
Looks promising 👍

**Comment by jan-molak** [comment]
The website engine is now migrated from ESDoc to Docusaurus on `main`. The website will be published as part of the Serenity/JS 3.0 release.
