### ISSUE TITLE
SerenityBDDReporter

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#162]
[`SerenityBDDReporter`](https://github.com/jan-molak/serenity-js/blob/master/packages/core/src/reporting/serenity_bdd_reporter.ts) should be improved to:
- [x] work with the latest version of TypeScript #156 #105
- [ ] make it easier to add custom domain events #161 #126 #59
- [ ] support additional tags #132 and improve tag handling in general #110 
- [ ] correctly handle mocha's before and after hooks #171 #104 
- [x] support multi-example scenarios #168 #220

**Comment by san-ouadghiri** [comment]
Stay strong /o/ (chearleader mode) !

**Comment by san-ouadghiri** [comment]
Hope you're still doing good. I look forward to seeing the Jest integration (as this seem to be a prerequisite). Stay brave :)!

**Comment by jan-molak** [comment]
Thanks, much appreciated! There's quite a few things I needed to improve, you can see the progress so far on the [`2.0` branch](https://github.com/jan-molak/serenity-js/tree/2.0)

**Comment by jan-molak** [comment]
The new `SerenityBDDReporter` is available as part of the [`@serenity-js/serenity-bdd` module](https://serenity-js.org/modules/serenity-bdd/). Thanks for your patience and support!
